version: '3.8'

services:

  mongo:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: scoringdb
    volumes:
      - mongo-data3:/data/db
    command: mongod --auth
    ports:
      - "27017:27017"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - backend

  mongo-express:
    image: mongo-express
    ports:
      - "8082:8082"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_SERVER: mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - backend

volumes:
  mongo-data3:

networks:
  backend: