server:
  connection-timeout: 10s
spring:
  mvc:
    servlet:
      path: /api
  application:
    name: scoring
  data:
    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017/scoringdb?authSource=admin
